First week
dmitriykryukov/kryukov-loft-taxi pull request #1
Opened 2021-01-18 03:54 UTC by dmitriykryukov

### **Первая неделя**
**Добавленны:**
- компонента страницы “Логин”
- компонента страницы “Регистрация”
- компонента страницы “Карта”
- компонента страницы “Профиль” (TODO нужно доверстать )
- Header

![image](https://user-images.githubusercontent.com/48837886/104870463-6df9f500-58fd-11eb-968a-d72bc938e243.png)
![image](https://user-images.githubusercontent.com/48837886/104870489-810cc500-58fd-11eb-9deb-317e37b20f2e.png)
![image](https://user-images.githubusercontent.com/48837886/104870507-8d911d80-58fd-11eb-95e5-ff46a9783c01.png)

2021-01-18 12:00 UTC, R-Oscar requested changes

2021-01-18 12:00 UTC, R-Oscar commented on src/App.js
>  const toggleOnLogin = () => {
Нейминг сбивает с толку, почему хендлер для логаута называется `logOut`, а хендлер для логина - `toggleOnLogin`? Нужно выбрать что-то одно

2021-01-18 12:00 UTC, R-Oscar commented on src/App.js
> +  console.log('toggleOnLogin')
Все консоль логи нужно убрать

2021-01-18 12:00 UTC, R-Oscar commented on src/assets/jss/Colors.js
> +  backgrnd: '#1C1A19',
Лучше не сокращать и назвать полностью background

2021-01-18 12:00 UTC, R-Oscar commented on src/components/Header.js
> +    <div>
Этот `<div>` обязателен? Давай уберем, зачем нам лишняя обертка

2021-01-18 12:00 UTC, R-Oscar commented on src/components/LoginForm.js
> +            onChange={(e) => setEmail(e.target.value)}
Надо местами поменять, здесь `setPassword` должно быть, а сверху `setEmail`

2021-01-18 12:00 UTC, R-Oscar commented on src/components/Header.js
> +  const { togglePage } = props
Здесь и далее лучше и проще деструктуризацию пропсов делать прямо в параметре, то есть
`export default function Header({ togglePage }) {`

2021-01-18 12:00 UTC, R-Oscar commented on src/components/MapPage.js
> +                <MenuItem value={'Пулково'}>Пулково (LED)</MenuItem>
Тут лучше вынести эти значения в константу с массивом, например
`const ROUTES = ['Пулково', ..., 'Мариинский театр'];`

И потом делать `{ROUTES.map()}`

https://ru.reactjs.org/docs/lists-and-keys.html

2021-01-18 12:00 UTC, R-Oscar commented on src/components/MapPage.js
> +  const [isAddressFrom, setAddressFrom] = React.useState('');
Обычно префикс `is` в названии переменной означает булевый тип, здесь же - просто строка, поэтому лучше назвать просто `addressFrom` и `addressTo`

2021-01-18 12:00 UTC, R-Oscar commented on src/components/MapPage.js
> +            <div className={classes.card}>
Перечисление тарифов это тоже список, его можно выразить в виде массива с объектами
```
  [{
    name: "Стандарт",
    price: 150
  },
  ...
  ]
```

И делать .map по аналогии с константой ROUTES, про которую я писал выше

2021-01-18 12:00 UTC, R-Oscar commented on src/layouts/MainPage.js
> +    setTooglePage(!isTooglePage)
Переходы по страницам немного не так должны работать. У тебя получается два варианта: карта или профиль. Страниц должно быть как минимум 3: карта, профиль, авторизация (регистрация)

Поэтому тут нужна константа PAGES которая будет такого вида:
```
const PAGES = {
  map: <Map />,
  ...
};
```

А в стейте будет храниться `currentPage` (например тот же map)
И тогда в рендере будет:
`{PAGES[currentPage]}`

2021-01-20 18:06 UTC, dmitriykryukov commented on src/components/MapPage.js
> +            <div className={classes.card}>
Я это реализую в следующем Pull request

2021-01-21 06:13 UTC, R-Oscar requested changes

2021-01-21 06:13 UTC, R-Oscar commented on src/components/MapPage.js
> +                {ROUTES.map(route =>  <MenuItem >{route}</MenuItem>) }
Тут нужно добавить свойство key
https://ru.reactjs.org/docs/lists-and-keys.html#keys

2021-01-21 16:43 UTC, R-Oscar approved these changes

2021-01-21 16:46 UTC, merged